/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
// Copyright (c) 2013 Mikhail Afanasov and DeepSe group. All rights reserved.// Use of this source code is governed by a BSD-style license that can be// found in the LICENSE file.
package parsers.configuration;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CONTEXTGROUP = 9;
  /** RegularExpression Id. */
  int CONFIGURATION = 10;
  /** RegularExpression Id. */
  int LAYERED = 11;
  /** RegularExpression Id. */
  int IMPLEMENTATION = 12;
  /** RegularExpression Id. */
  int ISDEFAULT = 13;
  /** RegularExpression Id. */
  int ISERROR = 14;
  /** RegularExpression Id. */
  int CONTEXTS = 15;
  /** RegularExpression Id. */
  int GROUPS = 16;
  /** RegularExpression Id. */
  int COMPONENTS = 17;
  /** RegularExpression Id. */
  int USES = 18;
  /** RegularExpression Id. */
  int PROVIDES = 19;
  /** RegularExpression Id. */
  int INTERFACE = 20;
  /** RegularExpression Id. */
  int INCLUDE = 21;
  /** RegularExpression Id. */
  int AS = 22;
  /** RegularExpression Id. */
  int LEXEME = 23;
  /** RegularExpression Id. */
  int EQUALS = 24;
  /** RegularExpression Id. */
  int RARROW = 25;
  /** RegularExpression Id. */
  int LARROW = 26;
  /** RegularExpression Id. */
  int SEMICOLON = 27;
  /** RegularExpression Id. */
  int COMMA = 28;
  /** RegularExpression Id. */
  int OCB = 29;
  /** RegularExpression Id. */
  int CCB = 30;
  /** RegularExpression Id. */
  int ORB = 31;
  /** RegularExpression Id. */
  int CRB = 32;
  /** RegularExpression Id. */
  int INCLUDENAME = 33;
  /** RegularExpression Id. */
  int DIRECTORY = 34;
  /** RegularExpression Id. */
  int FULLNAME = 35;
  /** RegularExpression Id. */
  int NAME = 36;
  /** RegularExpression Id. */
  int STRING_LITERAL = 37;
  /** RegularExpression Id. */
  int CHAR = 38;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int ML_COMMENT_STATE = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<token of kind 1>",
    "\"/*\"",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"*/\"",
    "<token of kind 8>",
    "\"context group\"",
    "\"configuration\"",
    "\"layered\"",
    "\"implementation\"",
    "\"is default\"",
    "\"is error\"",
    "\"contexts\"",
    "\"context groups\"",
    "\"components\"",
    "\"uses\"",
    "\"provides\"",
    "\"interface\"",
    "\"#include\"",
    "\"as\"",
    "<LEXEME>",
    "\"=\"",
    "\"->\"",
    "\"<-\"",
    "\";\"",
    "\",\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "<INCLUDENAME>",
    "<DIRECTORY>",
    "<FULLNAME>",
    "<NAME>",
    "<STRING_LITERAL>",
    "<CHAR>",
  };

}
